config/routes.rb
Langleycms::Application.routes.draw do

  namespace :refinery do
    namespace :blog do
      namespace :admin do
      end
    end
  end

  resources :customs

  resources :rooms

  resources :room_types do
    collection do
      get 'search'
    end

    get 'sort_by/:sort_option', :to=>'room_types#sort_by'
  end

  resources :people

  resources :business_days

  resources :bookings


  #namespace :refinery do
  #  match 'last-minute/:sort_option'=>'pages#sort_by', :as=>'pages_sort_by', :via=>'get'
  #end
  #match 'last-minute/:sort_option'=>'room_types#index', :as=>'sort_by'

  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  #mount the engine(RefineryCMS) into an application
  mount Refinery::Core::Engine, :at => '/'
  #root :to => 'bookings#show'
end

app/models/custom.rb
class Custom < ActiveRecord::Base
  has_many :peoples

  validates_presence_of :number_of_adults
end

app/controllers/customs_controller.rb
class CustomsController < ApplicationController
  # GET /customs
  # GET /customs.json
  def index
    @customs = Custom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customs }
    end
  end

  # GET /customs/1
  # GET /customs/1.json
  def show
    @custom = Custom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @custom }
    end
  end

  # GET /customs/new
  # GET /customs/new.json
  def new
    @custom = Custom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @custom }
    end
  end

  # GET /customs/1/edit
  def edit
    @custom = Custom.find(params[:id])
  end

  # POST /customs
  # POST /customs.json
  def create
    @custom = Custom.new(params[:custom])

    respond_to do |format|
      if @custom.save
        format.html { redirect_to @custom, notice: 'Custom was successfully created.' }
        format.json { render json: @custom, status: :created, location: @custom }
      else
        format.html { render action: "new" }
        format.json { render json: @custom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customs/1
  # PUT /customs/1.json
  def update
    @custom = Custom.find(params[:id])

    respond_to do |format|
      if @custom.update_attributes(params[:custom])
        format.html { redirect_to @custom, notice: 'Custom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @custom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customs/1
  # DELETE /customs/1.json
  def destroy
    @custom = Custom.find(params[:id])
    @custom.destroy

    respond_to do |format|
      format.html { redirect_to customs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/views/customs/_form.html.erb
<%= form_for(@custom) do |f| %>
  <% if @custom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom.errors.count, "error") %> prohibited this custom from being saved:</h2>

      <ul>
      <% @custom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_of_people %><br />
    <%= f.number_field :number_of_people %>
  </div>
  <div class="field">
    <%= f.label :number_of_children %><br />
    <%= f.number_field :number_of_children %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customs/edit.html.erb
<h1>Editing custom</h1>

<%= render 'form' %>

<%= link_to 'Show', @custom %> |
<%= link_to 'Back', customs_path %>

app/views/customs/index.html.erb
<h1>Listing customs</h1>

<table>
  <tr>
    <th>Number of people</th>
    <th>Number of children</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customs.each do |custom| %>
  <tr>
    <td><%= custom.number_of_people %></td>
    <td><%= custom.number_of_children %></td>
    <td><%= custom.email %></td>
    <td><%= link_to 'Show', custom %></td>
    <td><%= link_to 'Edit', edit_custom_path(custom) %></td>
    <td><%= link_to 'Destroy', custom, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Custom', new_custom_path %>

app/views/customs/new.html.erb
<h1>New custom</h1>

<%= render 'form' %>

<%= link_to 'Back', customs_path %>

app/views/customs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number of people:</b>
  <%= @custom.number_of_people %>
</p>

<p>
  <b>Number of children:</b>
  <%= @custom.number_of_children %>
</p>

<p>
  <b>Email:</b>
  <%= @custom.email %>
</p>


<%= link_to 'Edit', edit_custom_path(@custom) %> |
<%= link_to 'Back', customs_path %>